# Generated by Django 3.1.2 on 2020-11-06 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quatity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='quatity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quatity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quatitySelled',
            new_name='quantitySelled',
        ),
    ]
